// Date: 18.05.2014 13:41:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.modjam.terrifictransportation.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CoveyorImportExportHollow extends ModelBase
{
  //fields
    ModelRenderer Main1;
    ModelRenderer SideSlice1;
    ModelRenderer SideSlice2;
    ModelRenderer ImportBox1;
    ModelRenderer Shape1;
    ModelRenderer ImportBox2;
    ModelRenderer Main2;
    ModelRenderer Main4;
    ModelRenderer Main3;
  
  public CoveyorImportExportHollow()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Main1 = new ModelRenderer(this, 0, 0);
      Main1.addBox(0F, -1F, -8F, 5, 2, 16);
      Main1.setRotationPoint(-8F, 23F, 0F);
      Main1.setTextureSize(64, 64);
      Main1.mirror = true;
      setRotation(Main1, 0F, 0F, 0F);
      SideSlice1 = new ModelRenderer(this, 0, 23);
      SideSlice1.addBox(-8F, 0F, -1F, 16, 1, 2);
      SideSlice1.setRotationPoint(0F, 21F, -7F);
      SideSlice1.setTextureSize(64, 64);
      SideSlice1.mirror = true;
      setRotation(SideSlice1, 0F, 0F, 0F);
      SideSlice2 = new ModelRenderer(this, 0, 19);
      SideSlice2.addBox(-8F, 0F, -1F, 16, 1, 2);
      SideSlice2.setRotationPoint(0F, 21F, 7F);
      SideSlice2.setTextureSize(64, 64);
      SideSlice2.mirror = true;
      setRotation(SideSlice2, 0F, 0F, 0F);
      ImportBox1 = new ModelRenderer(this, 20, 50);
      ImportBox1.addBox(-1F, -5F, -1F, 8, 10, 2);
      ImportBox1.setRotationPoint(-7F, 16F, -7F);
      ImportBox1.setTextureSize(64, 64);
      ImportBox1.mirror = true;
      setRotation(ImportBox1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 20, 50);
      Shape1.addBox(-1F, -5F, -1F, 8, 10, 2);
      Shape1.setRotationPoint(-7F, 16F, 7F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      ImportBox2 = new ModelRenderer(this, 1, 49);
      ImportBox2.addBox(-1F, -1F, -6F, 8, 2, 12);
      ImportBox2.setRotationPoint(-7F, 12F, 0F);
      ImportBox2.setTextureSize(64, 64);
      ImportBox2.mirror = true;
      setRotation(ImportBox2, 0F, 0F, 0F);
      Main2 = new ModelRenderer(this, 0, 0);
      Main2.addBox(-2F, 0F, 0F, 5, 2, 16);
      Main2.setRotationPoint(5F, 22F, -8F);
      Main2.setTextureSize(64, 64);
      Main2.mirror = true;
      setRotation(Main2, 0F, 0F, 0F);
      Main4 = new ModelRenderer(this, 17, 11);
      Main4.addBox(0F, 0F, 0F, 6, 2, 5);
      Main4.setRotationPoint(-3F, 22F, 3F);
      Main4.setTextureSize(64, 64);
      Main4.mirror = true;
      setRotation(Main4, 0F, 0F, 0F);
      Main3 = new ModelRenderer(this, 12, 11);
      Main3.addBox(0F, 0F, 0F, 6, 2, 5);
      Main3.setRotationPoint(-3F, 22F, -8F);
      Main3.setTextureSize(64, 64);
      Main3.mirror = true;
      setRotation(Main3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Main1.render(f5);
    SideSlice1.render(f5);
    SideSlice2.render(f5);
    ImportBox1.render(f5);
    Shape1.render(f5);
    ImportBox2.render(f5);
    Main2.render(f5);
    Main4.render(f5);
    Main3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
